### ISSUE TITLE
Automate version bumping for ckeditor5-* dependencies

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-dev-env#13]
ckeditor5-\* dependencies of v0.2.0 have been released using this [crude bash script](https://gist.github.com/oleq/21ff20252b5c7bda62ae959ca720b414) that I had created. It's not perfect but it did the job.

This kind of automation should become a part of project's gulp ecosystem because it will be needed once in a couple of weeks for years to come and there will be more and more dependencies to handle, way to much to do it manually. 

There are several cases of ckeditor5-\* dependencies to be handled in the script:
1. A new repository (0.0.1 in package.json) which has no Git tag yet -> bumping version
2. An existing repository (X.Y.Z in package.json) which has vX.Y.Z Git tag.
   1. Repo has not been changed since vX.Y.Z -> no version bumping
   2. Repo has been changed since vX.Y.Z -> bumping version

There's also the question what to do with path/minor/major version bumping. It has been quite easy because all the dependencies in ckeditor5 v0.1.0->0.2.0 got a "minor bump". But what if some repositories were to be bumped as patches, some as minor and some as major version? It should be configurable somehow.

**Comment by oleq** [comment]
> There's also the question what to do with path/minor/major version bumping. It has been quite easy because all the dependencies in ckeditor5 v0.1.0->0.2.0 got a "minor bump". But what if some repositories were to be bumped as patches, some as minor and some as major version? It should be configurable somehow.

The syntax could be like `gulp bump minor ckeditor5-headings patch ckeditor5-undo major`.

**Comment by Reinmar** [comment]
There's a separate discussion about releasing here: https://github.com/ckeditor/ckeditor5-design/issues/145.

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/19.
