### ISSUE TITLE
Working directory of exec's function `sh` should be set to package's dir

### ISSUE THREAD

**Issue by maxbarnas** [ckeditor/ckeditor5-dev-env#2]
Right now function `sh` (invoked by `gulp exec --task sh`) is not changing working directory. Every command is run in `ckeditor5/`. 

This in practice makes `sh` useless.

**Comment by Reinmar** [comment]
In https://github.com/ckeditor/ckeditor5/issues/269 I thought that `shExec` is async, but it's not. So it's really simply missing changing a cwd.
