### ISSUE TITLE
Exec: Running your custom functions

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-dev-env#21]
Since the exec task was extracted from ckeditor5 to this package and since this package is installed through npm (so it's deep inside `node_modules`), it's harder to create your own temporary functions.

I think that we need to allow passing any path to `--task` parameter. But a reasonable workaround or even a quite nice solution is to create your function as an executable JS file:

``` js
#!/usr/bin/env node

'use strict';

console.log( process.cwd() );
```

And run it like this:

```
gulp exec --task sh --cmd '/path/to/my-function.js'
```

**Comment by maxbarnas** [comment]
We just need to make sure proper working directory is set for such script and this should work nicely. 

But if we are thinking about writing scripts, then maybe we can throw away `gulp exec` sorcery and allow importing code **to** the script, that will run it over all repositories. Then we just run this script and all the trickery is done by imported code.

Example of `some-script.js`:
```js
#!/usr/bin/env node

'use strict';

require( 'exec-on-repos' )( () => {
  console.log( process.cwd() );
} );
```
And then simply:
```sh
$ ./some-script.js
```
This might be too much effort for such a rarely used functionality, but hey! it is discussion after all 😄.

**Comment by Reinmar** [comment]
`gulp exec` doesn't contain any trickery. It's just a matter of allowing passing any path to `--task` option. Right now the path must be relative to the task file which is somewhere deep inside the package.

**Comment by Reinmar** [comment]
But I might have not understood your comment properly, so feel free to clarify if I got something wrong :D.

**Comment by maxbarnas** [comment]
What I proposed was totally different approach to running tasks. I considered it worth sharing if we plan to heavily use `gulp exec` scripts. Most probably an overkill.

Of course the simplest and quickest solution is just to allow specifying task files, like you proposed.

**Comment by Reinmar** [comment]
I want to make a list of examples how to use this task, so few more things:

```
gulp exec --task sh --cmd 'sed -i "" "s/ckeditor5-dev-lint/@ckeditor\/ckeditor5-dev-lint/" gulpfile.js'
```

```
gulp exec --task sh --cmd 'npm uninstall --save-dev ckeditor5-dev-lint && npm i --save-dev @ckeditor/ckeditor5-dev-lint'
```

**Comment by Reinmar** [comment]
Another useful script – releasing all packages:

```
gulp exec --include-root --task sh --cmd "npm version minor && git push --follow-tags"
```

**Comment by Reinmar** [comment]
I've got another nice example:

```js
#!/usr/bin/env node

'use strict';

const fs = require( 'fs' );
const path = require( 'path' );
const glob = require( 'glob' );

const testsPath = path.join( process.cwd(), 'tests' );

for ( const filePath of glob.sync( path.join( testsPath, '**', '*.js' ) ) ) {
	// Skip manual tests. They should be recognised by having an accompanying
	// .md file. Checking them by the path will also filter out automated ticket tests.
	if ( fs.existsSync( filePath.replace( /\.js$/, '.md' ) ) ) {
		console.log( filePath );

		continue;
	}

	const fileContent = fs.readFileSync( filePath, 'utf-8' ).replace( /from '\/(ckeditor5|tests)/g, 'from \'$1' );

	fs.writeFileSync( filePath, fileContent );
}
```

**Comment by Reinmar** [comment]
Couple more interesting executions:

* Print last tags:

  ```
  gulp exec --task sh --cmd "git describe --abbrev=0"
  ```

* Print commits since last tag:

  ```
  gulp exec --task sh --cmd "git log \`git describe --tags --abbrev=0\`..HEAD --oneline"
  ```

**Comment by pomek** [comment]
Moved to: https://github.com/ckeditor/ckeditor5-dev/issues/12
